services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/base/dockerfiles
    container_name: ${CONTAINER_NAME}
    image: rocio/ubbase
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs
    networks:
      netrocio:
        ipv4_address: ${IP_WEB}
networks:
  netrocio:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
