apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtaller-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webtaller
  template:
    metadata:
      labels:
        app: webtaller
    spec:
      containers:
      - name: webtaller
        image: rocio21/webtallerclase:latest
        ports:
        - containerPort: 80