apiVersion: v1 # Versión de la API de Kubernetes para servicios de red.
kind: Service # Tipo de recurso Service: sirve para dar una IP estable al despliegue de Nginx.
metadata: # Datos para identificar este servicio en el clúster.
  name: {{ .Values.app.container.name }}-nginx-service # Nombre del servicio para el servidor web Nginx.
  namespace: {{ .Release.Namespace }} # Se crea en el mismo namespace que el resto de componentes.
spec: # Definición de cómo funciona la red de este servicio.
  type: ClusterIP # Tipo ClusterIP: solo es accesible desde dentro del clúster (el Ingress será su puente al exterior).
  selector: # La "mira telescópica" para encontrar los pods de Nginx.
    app: {{ .Values.app.container.name }}-nginx # Busca pods que tengan esta etiqueta de aplicación Nginx.
    app.kubernetes.io/instance: {{ .Release.Name }} # Filtra también por la instancia específica de Helm.
  ports: # Configuración de los puertos de red.
    - name: http # Nombre identificativo para el tráfico web.
      port: 80 # Puerto en el que el servicio escuchará internamente en el clúster.
      targetPort: 80 # Puerto real del contenedor de Nginx al que se redirige el tráfico.