services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/node_next/dockerfiles
    container_name: ${CONTAINER_NAME}
    image: rocio/node_next
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs
    networks:
      netrocionext:
        ipv4_address: ${IP_WEB}
networks:
  netrocionext:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
