server {
    listen 80;
    server_name localhost;
    
    # Redirigir el acceso a la raíz hacia /instituto conservando el HOST y Puerto original
    location = / {
        return 301 $scheme://$http_host/instituto;
    }

    # Proxy a Next.js (que correrá internamente en el 3000)
    location / {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Interceptar errores de Next.js para mostrar nuestra página
        proxy_intercept_errors on;
    }

    # Página de error personalizada
    error_page 404 /error_custom.html;
    error_page 500 502 503 504 /error_custom.html;
    
    location = /error_custom.html {
        root /var/www/html;
        internal;
    }
}
