apiVersion: v1
kind: Service
metadata:
  name: webtaller-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort      
  selector:
    app: webtaller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32227  